### PR TITLE
Update commands.js

### PR DESCRIPTION
**Pull request by Mask1nen**
Since queue is locked all the time during stream now and not just sunday.

### CODE REVIEW

**Comment by netux** [comment]
Sorry if I'm late, is this still like this? If so I will push.

**Comment by Mask1nen** [comment]
Don't push yet.

**Comment by Larry1123** [comment]
I'm not 100% sure that we should have removed the sub sunday command. We still do have sunday as sub only. For just on stream it is not locked the whole time, only when Nightblue does lock it.

**Comment by Mask1nen** [comment]
Yeah should probably revert that push. My bad :(

**Comment by netux** [comment]
Reverted [3e91505](https://github.com/nightbloo/nb3bot/commit/3e915056ae62c9a07e3b531d1e153d7cdbb70ec6)

**Pull request merged**
